name: Linter

on: push

jobs:
  lint:
    name: Linting Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      
      - name: Running Superlinter
        uses: github/super-linter@2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
